### ISSUE TITLE
Spec file doesn't check location of declaration of Person class

### ISSUE THREAD

**Issue by sivaraam** [learn-co-curriculum/classes-and-instances-lab-ruby#3]
The current Rspec file for this lab doesn't seem to checking whether the `Person` class is being declared in the `lib/person.rb` file as a result of which the test passes even when the Person class is declared in the `lib/dog.rb` file but the further tests don't pass as they require the methods to be in the `lib/person.rb` file

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestion. We updated the specs to verify if the classes are declared in the appropriate files.

As always, thanks for contributing! 💙
